window.DEALS_DATA = {"updated": "2026-10-04", "deals": [
  {"name": "Cloud Island Baby Girls' 3pk Floral Pointelle Sleep N' Play", "store": "Target", "cat": "Sleepwear", "size": "Baby", "was": 15, "now": 10.5, "emoji": "🌸", "url": "https://www.target.com/c/baby-clothing-clearance/-/N-5tg40"},
  {"name": "Carter's Just One You Baby Boys' 4pc T-Shirt and Shorts Set", "store": "Target", "cat": "Sets", "size": "Baby", "was": 16, "now": 11.2, "emoji": "👕", "url": "https://www.target.com/c/baby-clothing-clearance/-/N-5tg40"},
  {"name": "Cloud Island Baby Boys' 2pc Johnny Collar Polo Shirt and Shorts Set", "store": "Target", "cat": "Sets", "size": "Baby", "was": 12, "now": 6, "emoji": "👔", "url": "https://www.target.com/c/baby-clothing-clearance/-/N-5tg40"},
  {"name": "Carter's Just One You Baby Girls' 2pc Rose Tank Top and Shorts Set", "store": "Target", "cat": "Sets", "size": "Baby", "was": 12, "now": 6, "emoji": "🌹", "url": "https://www.target.com/c/baby-clothing-clearance/-/N-5tg40"},
  {"name": "Baby Boy Carter's Dinosaur Short-Sleeve Romper", "store": "Kohl's", "cat": "Rompers", "size": "Baby", "was": 18, "now": 9, "emoji": "🦖", "url": "https://www.kohls.com/catalog/sale-baby-clothing.jsp?CN=Promotions%3ASale+AgeAppropriate%3AKids+ChildAgeRange%3ABaby+Department%3AClothing"},
  {"name": "Baby Girl Carter's 2pc Floral Top & Short Set", "store": "Kohl's", "cat": "Sets", "size": "Baby", "was": 29, "now": 17.4, "emoji": "🌼", "url": "https://www.kohls.com/catalog/sale-baby-clothing.jsp?CN=Promotions%3ASale+AgeAppropriate%3AKids+ChildAgeRange%3ABaby+Department%3AClothing"},
  {"name": "Carter's Baby Bodysuits Multi-Pack (50% off)", "store": "Macy's", "cat": "Bodysuits", "size": "Baby", "was": 26, "now": 13, "emoji": "👶", "url": "https://www.macys.com/shop/sale/by-category/kids-baby/baby?id=64780"}
]};
